version: '3.8'

networks: 
  lv_net:

services:

  mysql:
    image: mysql:8.0
    container_name: mysql-lv
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: veterinaria_app
    ports: 
      - 33060:3306
    volumes: 
      - ./database:/var/lib/mysql
    networks: 
      - lv_net

  phpmyadmin:
    image: phpmyadmin:5.0
    container_name: phpmyadmin-lv
    restart: always
    environment: 
      PMA_HOST: mysql
    ports: 
      - 8080:80
    depends_on: 
      - mysql
    networks: 
      - lv_net

  nginx:
    image: nginx:1.19
    container_name: nginx-lv
    restart: always
    ports: 
      - 8000:80
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - php
    networks:
      - lv_net

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-lv
    volumes: 
      - ./src:/var/www/html
    ports: 
      - 9000:80
    networks: 
      - lv_net